### PR TITLE
Issue 26 / FUGR determination of include 

### PR DESCRIPTION
**Pull request by ed-holland**
Finally, the correct Pull Request created. time to go to bed.

### CODE REVIEW

**Comment by larshp** [comment]
@ed-holland did this work out? the code looks okay, however I've not tried it

in all cases its better than before

**Comment by ed-holland** [comment]
It works nicely for the includes of a fuba (type 3). For type 2, the include is also determined and passed, but it is not used. Nothing happens in this case. Debugging shows that it is cleared but i have no idea how this happened.

**Comment by larshp** [comment]
if you set the PR to "Ready for review" then we can merge it

**Comment by ed-holland** [comment]
Now it works as it should be...

**Comment by larshp** [comment]
thanks 👍

**Pull request merged**
