### PR TITLE
Issue 58

### PR DESCRIPTION
**Pull request by ed-holland**
Code still contains debug and commented parts.

### CODE REVIEW

**Comment by larshp** [comment]
ref #58

**Comment by ed-holland** [comment]
Why is the linter having problems with the code?

**Comment by larshp** [comment]
see https://github.com/abaplint/abaplint-abap-backend/pull/60/checks

add `seoc_version_active` and `seoc_clstype_class` as global constants in the abaplint.json configuration

**Comment by sbcgua** [comment]
could i also kindly ask to keep it 702 compatible please :) I'm using it in 731 and it is always a pain to downport :(

**Comment by ed-holland** [comment]
> could i also kindly ask to keep it 702 compatible please :) I'm using it in 731 and it is always a pain to downport :(

the abaplint.json is set to 702. What is not getting detected?

**Comment by ed-holland** [comment]
> could i also kindly ask to keep it 702 compatible please :) I'm using it in 731 and it is always a pain to downport :(

See you changed the config accordingly. I'll change accordingly.

**Comment by ed-holland** [comment]
Creating new one

**Pull request closed without merging**
