### PR TITLE
Downport 731

### PR DESCRIPTION
**Pull request by sbcgua**
OK, I guess this part is ready for now (#15 )

- downport
- docs update
- linter conf change
  - 702
  - allow defines (<740 without macros is a pain)
  - allow non top definition (please ! this is much more readable and logical)
  - remove constraint on FS naming (please ! FSs are usually iterators and already have those brackets, adding prefixes to them is imho unnesessary)

### CODE REVIEW

**Comment by larshp** [comment]
at least no macros please

**Comment by sbcgua** [comment]
ok, will have a look how to remove them

**Comment by larshp** [comment]
similar to https://github.com/larshp/abapGit/pull/3185 ?

**Comment by sbcgua** [comment]
yeah ... readability is a must ... guess it should be possible to make a universal utility for this ... =)))) maybe ...

**Comment by sbcgua** [comment]
done

**Pull request merged**
